include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable string interpolation warning
    unnecessary_brace_in_string_interps: false
    # Disable underscore warning
    unnecessary_underscores: false
