name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.3"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      # ---------- TEST FLOW ----------

      # Optional but good for "senior" quality
      - name: Run static analysis
        run: flutter analyze

      # This runs all your tests under `test/`
      # (unit + widget tests, e.g. HomeProvider, HomePage)
      - name: Run unit & widget tests
        run: flutter test

      # If later you add E2E tests with integration_test package in `integration_test/`,
      # you can enable this step:
      # - name: Run end-to-end tests
      #   run: flutter test integration_test

      # ---------- BUILD APK ----------

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
